name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mytestdb  # <-- Dedicated test DB name
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        env:
          DATABASE_URL: postgresql://user:password@localhost:5432/mytestdb
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          playwright install  # if you use Playwright for e2e tests
      
      - name: Install Playwright dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          libgtk-4-1 libgraphene-1.0-0 libwoff2-1 libvpx9 libevent-2.1-7 libopus0 \
          gstreamer1.0-libav gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
          gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-gl \
          gstreamer1.0-gtk3 gstreamer1.0-tools gstreamer1.0-x libflite1 libavif16 \
          libharfbuzz-icu0 libsecret-1-0 libhyphen0 libmanette-0.2-0 libgles2-mesa libx264-160

      - name: Run tests
        env:
          DATABASE_URL: postgresql://user:password@localhost:5432/mytestdb
        run: |
          source venv/bin/activate
          
          # 1) Unit tests
          pytest tests/unit/ --cov=src --junitxml=test-results/junit.xml
          
          # 2) Integration tests
          pytest tests/integration/
          
          # 3) Start app in background for E2E tests
          uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          SERVER_PID=$!
          echo "Waiting for server to start..."
          sleep 5
          
          # 4) E2E tests
          pytest tests/e2e/
          
          # 5) Stop server
          kill $SERVER_PID

  security:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build image
        run: docker build -t app:test .
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'app:test'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
  
  deploy:
    needs: security
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      
      - uses: docker/setup-buildx-action@v3
      
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            kaw393939/601_module9:latest
            kaw393939/601_module9:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=kaw393939/601_module9:cache
          cache-to: type=inline,mode=max
